# Generated by Django 4.0.2 on 2022-02-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kintai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField()),
                ('workingday', models.DateField(blank=True, null=True)),
                ('begintime', models.DateTimeField(blank=True, null=True)),
                ('finishtime', models.DateTimeField(blank=True, null=True)),
                ('breaktime', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kintai',
            },
        ),
        migrations.CreateModel(
            name='WorkingStatus',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('isworking', models.BooleanField()),
            ],
            options={
                'db_table': 'working_status',
            },
        ),
    ]
