# Generated by Django 4.0.2 on 2022-02-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintaiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Kintai',
            name='id', 
            field=models.AutoField(primary_key=True),
        )
    ]
