# Generated by Django 4.0.2 on 2023-01-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintaiapp', '0002_modify_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kintai',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
