# Generated by Django 4.0.2 on 2024-07-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintaiapp', '0003_alter_kintai_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_NYUUSYUKKOKEKKA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemNO', models.TextField(null=True)),
                ('meisyou', models.TextField(null=True)),
                ('HINMOKUType', models.TextField(null=True)),
                ('TANABAN_N', models.TextField(null=True)),
                ('SUURYOU', models.IntegerField()),
                ('KAISUU', models.IntegerField()),
                ('MEMO1', models.TextField(null=True)),
                ('MEMO2', models.TextField(null=True)),
                ('TANABINITIJI', models.DateTimeField(blank=True, null=True)),
                ('TANAIREBIMIN', models.DateTimeField(blank=True, null=True)),
                ('TANAOROSHINO', models.TextField(null=True)),
                ('TANAOROSHIBI', models.DateTimeField(blank=True, null=True)),
                ('TANAOROSHISAI', models.TextField(null=True)),
                ('TANAOROSHIKAISUU', models.IntegerField()),
                ('TANAOPrint', models.BooleanField()),
                ('TANAOPrintBI', models.DateTimeField(blank=True, null=True)),
                ('TANAOPrintSYA', models.TextField(null=True)),
                ('TANAOPrintSYAmei', models.TextField(null=True)),
                ('KUBUN', models.IntegerField(null=True)),
                ('MRPKANRISYA', models.TextField(null=True)),
                ('IDOUck', models.BooleanField()),
                ('IDOUbi', models.DateTimeField(blank=True, null=True)),
                ('IDOUsya', models.TextField(null=True)),
                ('IDOUsaki', models.TextField(null=True)),
            ],
            options={
                'db_table': 'T_NYUUSYUKKOKEKKA',
            },
        ),
    ]
