
# Memo: Default -> django.utils.log.py
# class: logging.StreamHandler
LOGGING:
  root:
    level: DEBUG
  version: 1
  formatters:
    standard:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    error:
      format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
  handlers:
    default:
      class: logging.StreamHandler
      stream: ext://sys.stderr
  loggers:
    console:
      handlers: [default]
      formatters: [standard]
      level: DEBUG